export type ProductSeed = {
  id: number;
  name: string;
  releaseDate: string | null;
  image: string;
  imageHover: string;
  imageDetail: string;
  gender: string;
  age: string;
  priceUsd: number;
  originalPriceUsd: number | null;
  onSale: string;
  color: string;
  colorDetail: string;
  franchise: string;
  productType: string;
  brand: string;
  category: string;
  sports: string;
  miAdidas: string;
  teamName: string;
  partner: string;
};

export const PRODUCTS: ProductSeed[] = [
  { id: 1, name: "NMD_R1 PRIMEKNIT SHOES", releaseDate: "2018-05-13", image: "1.jpg", imageHover: "1.jpg", imageDetail: "", gender: "men", age: "", priceUsd: 170, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "nmd", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 2, name: "SST TRACK JACKET", releaseDate: "2018-05-13", image: "2.jpg", imageHover: "2hover.jpg", imageDetail: "2.jpg", gender: "men", age: "", priceUsd: 75, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "adicolor", productType: "", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 3, name: "ULTRABOOST SHOES", releaseDate: "2018-05-13", image: "3.jpg", imageHover: "3hover.jpg", imageDetail: "3.jpg", gender: "men", age: "", priceUsd: 180, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "ultraboost", productType: "", brand: "", category: "shoes", sports: "running", miAdidas: "", teamName: "", partner: "" },
  { id: 4, name: "POD-S3.1 SHOES", releaseDate: "2018-05-13", image: "4.jpg", imageHover: "4hover.jpg", imageDetail: "4.jpg", gender: "men", age: "", priceUsd: 30, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "podsystem", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 5, name: "NEMEZIZ 18+ FIRM GROUND CLEATS", releaseDate: "2018-05-13", image: "5.jpg", imageHover: "5hover.jpg", imageDetail: "5.jpg", gender: "men", age: "", priceUsd: 290, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 6, name: "Harden Vol. 2 MVP Shoes", releaseDate: "2018-05-13", image: "6.jpg", imageHover: "6.jpg", imageDetail: "6.jpg", gender: "men", age: "", priceUsd: 160, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "basketball", miAdidas: "", teamName: "", partner: "" },
  { id: 7, name: "24/7 Shoes", releaseDate: "2018-05-13", image: "7.jpg", imageHover: "7hover.jpg", imageDetail: "7.jpg", gender: "men", age: "", priceUsd: 100, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 8, name: "Freak Ultra Primeknit Cleats", releaseDate: "2018-05-13", image: "8.jpg", imageHover: "8hover.jpg", imageDetail: "8.jpg", gender: "men", age: "", priceUsd: 180, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "football", miAdidas: "", teamName: "", partner: "" },
  { id: 9, name: "adilette Slides", releaseDate: "2018-05-13", image: "9.jpg", imageHover: "9hover.jpg", imageDetail: "9.jpg", gender: "men", age: "", priceUsd: 45, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "slides", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 10, name: "Terrex Swift R2 GTX Shoes", releaseDate: "2018-05-13", image: "10.jpg", imageHover: "10hover.jpg", imageDetail: "10.jpg", gender: "men", age: "", priceUsd: 135, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "outdoor", miAdidas: "", teamName: "", partner: "" },
  { id: 11, name: "Barricade 2018 Boost Shoes", releaseDate: "2018-05-13", image: "11.jpg", imageHover: "11hover.jpg", imageDetail: "11.jpg", gender: "men", age: "", priceUsd: 160, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "tennis", miAdidas: "", teamName: "", partner: "" },
  { id: 12, name: "3ST.002 Primeknit Shoes", releaseDate: "2018-05-13", image: "12.jpg", imageHover: "12hover.jpg", imageDetail: "12.jpg", gender: "men", age: "", priceUsd: 150, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "skateboarding", miAdidas: "", teamName: "", partner: "" },
  { id: 13, name: "Icon 4 Trainer Nations Shoes", releaseDate: "2018-05-13", image: "13.jpg", imageHover: "13hover.jpg", imageDetail: "13.jpg", gender: "men", age: "", priceUsd: 100, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "baseball", miAdidas: "", teamName: "", partner: "" },
  { id: 14, name: "Tour360 Knit Shoes", releaseDate: "2018-05-13", image: "14.jpg", imageHover: "14hover.jpg", imageDetail: "14.jpg", gender: "men", age: "", priceUsd: 180, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "golf", miAdidas: "", teamName: "", partner: "" },
  { id: 15, name: "Mi Z.N.E Hoddie", releaseDate: "2018-05-13", image: "15.jpg", imageHover: "15.jpg", imageDetail: "15.jpg", gender: "men", age: "", priceUsd: 120, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "hoddie", brand: "", category: "hoddie", sports: "", miAdidas: "customizable", teamName: "", partner: "" },
  { id: 16, name: "Deerupt Runner Shoes", releaseDate: "2018-05-13", image: "16.jpg", imageHover: "16hover.jpg", imageDetail: "16.jpg", gender: "men", age: "", priceUsd: 70, originalPriceUsd: 100, onSale: "sale", color: "", colorDetail: "", franchise: "", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 17, name: "Tiro 17 Training Pants", releaseDate: "2018-05-13", image: "17.jpg", imageHover: "17hover.jpg", imageDetail: "17.jpg", gender: "men", age: "", priceUsd: 45, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "pants", brand: "", category: "", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 18, name: "adidas Z.N.E. Hoodie 2", releaseDate: "2018-05-13", image: "18.jpg", imageHover: "18hover.jpg", imageDetail: "18.jpg", gender: "men", age: "", priceUsd: 100, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "hoodies_sweatshirts", brand: "athletics", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 19, name: "ID Jacket", releaseDate: "2018-05-13", image: "19.jpg", imageHover: "19hover.jpg", imageDetail: "19.jpg", gender: "men", age: "", priceUsd: 85, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "jackets", brand: "athletics", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 20, name: "FreeLift Prime Tee", releaseDate: "2018-05-13", image: "20.jpg", imageHover: "20hover.jpg", imageDetail: "20.jpg", gender: "men", age: "", priceUsd: 25, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "short_sleeve_shirts", brand: "", category: "0", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 21, name: "3-Stripes Tee", releaseDate: "2018-05-13", image: "21.jpg", imageHover: "21hover.jpg", imageDetail: "21.jpg", gender: "men", age: "", priceUsd: 35, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "t_shirts", brand: "originals", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 22, name: "Hélas Polo", releaseDate: "2018-05-13", image: "22.jpg", imageHover: "22hover.jpg", imageDetail: "22.jpg", gender: "men", age: "", priceUsd: 60, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "long_sleeve_shirts", brand: "originals", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 23, name: "Climachill Polo Shirt", releaseDate: "2018-05-13", image: "23.jpg", imageHover: "23hover.jpg", imageDetail: "23.jpg", gender: "men", age: "", priceUsd: 60, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "polo", sports: "tennis", miAdidas: "", teamName: "", partner: "" },
  { id: 24, name: "Ultimate365 Heather Polo Shirt", releaseDate: "2018-05-13", image: "24.jpg", imageHover: "24hover.jpg", imageDetail: "24.jpg", gender: "men", age: "", priceUsd: 75, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "polo", sports: "golf", miAdidas: "", teamName: "", partner: "" },
  { id: 25, name: "Manchester United Home Authentic Jersey", releaseDate: "2018-05-13", image: "25.jpg", imageHover: "25hover.jpg", imageDetail: "25.jpg", gender: "men", age: "", priceUsd: 130, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "jerseys", brand: "", category: "", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 26, name: "Alphaskin 3/4 Tech Tights", releaseDate: "2018-05-13", image: "26.jpg", imageHover: "26hover.jpg", imageDetail: "26.jpg", gender: "men", age: "", priceUsd: 60, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "tights", brand: "", category: "compression", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 27, name: "Alphaskin Sport Tee", releaseDate: "2018-05-13", image: "27.jpg", imageHover: "27hover.jpg", imageDetail: "27.jpg", gender: "men", age: "", priceUsd: 30, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "compression", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 28, name: "Ultimate365 Shorts", releaseDate: "2018-05-13", image: "28.jpg", imageHover: "28hover.jpg", imageDetail: "28.jpg", gender: "men", age: "", priceUsd: 65, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "shorts", brand: "", category: "", sports: "golf", miAdidas: "", teamName: "", partner: "" },
  { id: 29, name: "Supernova Singlet", releaseDate: "2018-05-13", image: "29.jpg", imageHover: "29hover.jpg", imageDetail: "29.jpg", gender: "men", age: "", priceUsd: 45, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "tank_tops", brand: "", category: "0", sports: "running", miAdidas: "", teamName: "", partner: "" },
  { id: 30, name: "Climacool Boxer Briefs 2 Pairs", releaseDate: "2018-05-13", image: "30.jpg", imageHover: "30hover.jpg", imageDetail: "30.jpg", gender: "men", age: "", priceUsd: 14, originalPriceUsd: 28, onSale: "sale", color: "", colorDetail: "", franchise: "", productType: "underwear", brand: "", category: "apparel", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 31, name: "Prime 4 Backpack", releaseDate: "2018-05-13", image: "31.jpg", imageHover: "31hover.jpg", imageDetail: "31.jpg", gender: "", age: "", priceUsd: 65, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "bags", brand: "", category: "accessories", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 32, name: "Climacool Tour Cap", releaseDate: "2018-05-13", image: "32.jpg", imageHover: "32.jpg", imageDetail: "32.jpg", gender: "", age: "", priceUsd: 30, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "hats", brand: "", category: "accessories", sports: "golf", miAdidas: "", teamName: "", partner: "" },
  { id: 33, name: "Trefoil No-Show Socks 6 Pairs", releaseDate: "2018-05-13", image: "33.jpg", imageHover: "33.jpg", imageDetail: "33.jpg", gender: "men", age: "", priceUsd: 20, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "socks", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 34, name: "Booklet Case iPhone X Suede", releaseDate: "2018-05-13", image: "34.jpg", imageHover: "34.jpg", imageDetail: "34.jpg", gender: "", age: "", priceUsd: 30, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "phone_cases", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 35, name: "Tempest Sunglasses", releaseDate: "2018-05-13", image: "35.jpg", imageHover: "35.jpg", imageDetail: "35.jpg", gender: "", age: "", priceUsd: 133, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "sunglasses", brand: "", category: "accessories", sports: "running", miAdidas: "", teamName: "", partner: "" },
  { id: 36, name: "UCL Finale Kiev Official Game Ball", releaseDate: "2018-05-13", image: "36.jpg", imageHover: "36.jpg", imageDetail: "36.jpg", gender: "", age: "", priceUsd: 165, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "balls", brand: "", category: "accessories", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 37, name: "DISTRICT_L1 Watch", releaseDate: "2018-05-13", image: "37.jpg", imageHover: "37.jpg", imageDetail: "37.jpg", gender: "", age: "", priceUsd: 130, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "watches", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 38, name: "Predator Pro Gloves", releaseDate: "2018-05-13", image: "38.jpg", imageHover: "38.jpg", imageDetail: "38.jpg", gender: "men", age: "", priceUsd: 120, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "gloves", brand: "", category: "accessories", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 39, name: "Argentina Home Scarf", releaseDate: "2018-05-13", image: "39.jpg", imageHover: "39.jpg", imageDetail: "39.jpg", gender: "men", age: "", priceUsd: 14, originalPriceUsd: 20, onSale: "sale", color: "", colorDetail: "", franchise: "", productType: "scarves", brand: "", category: "accessories", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 40, name: "Powerlift.3.1 Shoes", releaseDate: "2018-05-13", image: "40.jpg", imageHover: "40hover.jpg", imageDetail: "40.jpg", gender: "men", age: "", priceUsd: 90, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "0", sports: "weightlifting", miAdidas: "", teamName: "", partner: "" },
  { id: 41, name: "Golden Knights Home Authentic Pro Jersey", releaseDate: "2018-05-13", image: "41.jpg", imageHover: "41hover.jpg", imageDetail: "41.jpg", gender: "men", age: "", priceUsd: 180, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "0", sports: "hockey", miAdidas: "", teamName: "", partner: "" },
  { id: 42, name: "USA Volleyball Replica Tee", releaseDate: "2018-05-13", image: "42.jpg", imageHover: "42hover.jpg", imageDetail: "42.jpg", gender: "men", age: "", priceUsd: 40, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "0", sports: "volleyball", miAdidas: "", teamName: "", partner: "" },
  { id: 43, name: "Freak Head", releaseDate: "2018-05-13", image: "43.jpg", imageHover: "43.jpg", imageDetail: "43.jpg", gender: "", age: "", priceUsd: 90, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "0", sports: "lacrosse", miAdidas: "", teamName: "", partner: "" },
  { id: 44, name: "ASU Coach Polo", releaseDate: "2018-05-13", image: "44.jpg", imageHover: "44.jpg", imageDetail: "44.jpg", gender: "men", age: "", priceUsd: 75, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "athletics", category: "0", sports: "", miAdidas: "", teamName: "arizona_state_university", partner: "" },
  { id: 45, name: "TRI VNECK TEE", releaseDate: "2018-05-13", image: "45.jpg", imageHover: "45.jpg", imageDetail: "45.jpg", gender: "women", age: "", priceUsd: 30, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "0", sports: "football", miAdidas: "", teamName: "arizona_state_university", partner: "" },
  { id: 46, name: "Kaval Cuffed Pants", releaseDate: "2018-05-13", image: "46.jpg", imageHover: "46hover.jpg", imageDetail: "46.jpg", gender: "women", age: "", priceUsd: 65, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "podsystem", productType: "pants", brand: "originals", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 47, name: "Kaval Tee", releaseDate: "2018-05-13", image: "47.jpg", imageHover: "47hover.jpg", imageDetail: "47.jpg", gender: "women", age: "", priceUsd: 40, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "podsystem", productType: "tee", brand: "originals", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 48, name: "Kaval Hoodie", releaseDate: "2018-05-13", image: "48.jpg", imageHover: "48hover.jpg", imageDetail: "48.jpg", gender: "women", age: "", priceUsd: 80, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "podsystem", productType: "hoddie", brand: "originals", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 49, name: "3-Stripes Tee", releaseDate: "2018-05-13", image: "49.jpg", imageHover: "49hover.jpg", imageDetail: "49.jpg", gender: "women", age: "", priceUsd: 35, originalPriceUsd: 0, onSale: "", color: "", colorDetail: "", franchise: "adicolor", productType: "tee", brand: "originals", category: "0", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 50, name: "Ultraboost Shoes", releaseDate: null, image: "50.jpg", imageHover: "50hover.jpg", imageDetail: "50.jpg", gender: "women", age: "", priceUsd: 180, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "ultraboost", productType: "", brand: "", category: "shoes", sports: "running", miAdidas: "", teamName: "", partner: "" },
  { id: 51, name: "Arkyn Shoes", releaseDate: null, image: "51.jpg", imageHover: "51hover.jpg", imageDetail: "51.jpg", gender: "women", age: "", priceUsd: 98, originalPriceUsd: 140, onSale: "sale", color: "", colorDetail: "", franchise: "arkyn", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 52, name: "CrazyTrain Elite Shoes", releaseDate: null, image: "52.jpg", imageHover: "52hover.jpg", imageDetail: "52.jpg", gender: "women", age: "", priceUsd: 140, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 53, name: "Ultimafusion Shoes", releaseDate: null, image: "53.jpg", imageHover: "53hover.jpg", imageDetail: "53.jpg", gender: "women", age: "", priceUsd: 75, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "essentials", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 54, name: "Adilette Slides", releaseDate: null, image: "54.jpg", imageHover: "54hover.jpg", imageDetail: "54.jpg", gender: "women", age: "", priceUsd: 50, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "slides", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 55, name: "Terrex Choleah Padded Climaproof Boots", releaseDate: null, image: "55.jpg", imageHover: "55.jpg", imageDetail: "55.jpg", gender: "women", age: "", priceUsd: 130, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "outdoor", miAdidas: "", teamName: "", partner: "" },
  { id: 56, name: "adidas by Stella McCartney Barricade Boost Shoes", releaseDate: null, image: "56.jpg", imageHover: "56hover.jpg", imageDetail: "56.jpg", gender: "women", age: "", priceUsd: 130, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "tennis", miAdidas: "", teamName: "", partner: "adidas-by-stella-mccartney" },
  { id: 57, name: "Climacool Knit Shoes", releaseDate: null, image: "57.jpg", imageHover: "57hover.jpg", imageDetail: "57.jpg", gender: "women", age: "", priceUsd: 110, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "golf", miAdidas: "", teamName: "", partner: "" },
  { id: 58, name: "Predator 18.1 Firm Ground Cleats", releaseDate: null, image: "58.jpg", imageHover: "58hover.jpg", imageDetail: "58.jpg", gender: "women", age: "", priceUsd: 225, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "soccer", miAdidas: "", teamName: "", partner: "" },
  { id: 59, name: "Crazyflight X 2.0 Mid Shoes", releaseDate: null, image: "59.jpg", imageHover: "59hover.jpg", imageDetail: "59.jpg", gender: "women", age: "", priceUsd: 140, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "shoes", sports: "volleyball", miAdidas: "", teamName: "", partner: "" },
  { id: 60, name: "Mi Zx Flux Shoes", releaseDate: null, image: "60.jpg", imageHover: "60.jpg", imageDetail: "60.jpg", gender: "women", age: "", priceUsd: 100, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "customizable", teamName: "", partner: "" },
  { id: 61, name: "Trefoil Hoodie", releaseDate: null, image: "61.jpg", imageHover: "61hover.jpg", imageDetail: "61.jpg", gender: "women", age: "", priceUsd: 100, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "hoodies_sweatshirts", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 62, name: "3-Stripes Leggings", releaseDate: null, image: "62.jpg", imageHover: "62hover.jpg", imageDetail: "62.jpg", gender: "women", age: "", priceUsd: 40, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "tights", brand: "originals", category: "compression", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 63, name: "All Me Strappy Bra", releaseDate: null, image: "63.jpg", imageHover: "63hover.jpg", imageDetail: "63.jpg", gender: "women", age: "", priceUsd: 25, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "bras", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 64, name: "SST Track Jacket", releaseDate: null, image: "64.jpg", imageHover: "64hover.jpg", imageDetail: "64.jpg", gender: "women", age: "", priceUsd: 70, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "jackets", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 65, name: "3-Stripes Tee", releaseDate: null, image: "65.jpg", imageHover: "65hover.jpg", imageDetail: "65.jpg", gender: "women", age: "", priceUsd: 35, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "short_sleeve_shirts", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 66, name: "3-Stripes Tee", releaseDate: null, image: "66.jpg", imageHover: "66hover.jpg", imageDetail: "66.jpg", gender: "women", age: "", priceUsd: 40, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "long_sleeve_shirts", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 67, name: "Ultimate365 Polo Shirt", releaseDate: null, image: "67.jpg", imageHover: "67hover.jpg", imageDetail: "67.jpg", gender: "women", age: "", priceUsd: 60, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "originals", category: "polo", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 68, name: "Skirt", releaseDate: null, image: "68.jpg", imageHover: "68hover.jpg", imageDetail: "68.jpg", gender: "women", age: "", priceUsd: 25, originalPriceUsd: 50, onSale: "sale", color: "", colorDetail: "", franchise: "", productType: "dresses_and_skirts", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 69, name: "M10 Icon Shorts", releaseDate: null, image: "69.jpg", imageHover: "69hover.jpg", imageDetail: "69.jpg", gender: "women", age: "", priceUsd: 28, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "shorts", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 70, name: "Bra Top", releaseDate: null, image: "70.jpg", imageHover: "70hover.jpg", imageDetail: "70.jpg", gender: "women", age: "", priceUsd: 35, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "tank_tops", brand: "originals", category: "", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 71, name: "5PK CREATOR PLUS HAIRBAND", releaseDate: null, image: "71.jpg", imageHover: "71.jpg", imageDetail: "71.jpg", gender: "women", age: "", priceUsd: 14, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "headbands", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 72, name: "Interval Reversible Headband", releaseDate: null, image: "72.jpg", imageHover: "72.jpg", imageDetail: "72.jpg", gender: "", age: "", priceUsd: 7, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "headbands", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 73, name: "EQT Socks 1 Pair", releaseDate: null, image: "73.jpg", imageHover: "73hover.jpg", imageDetail: "73.jpg", gender: "women", age: "", priceUsd: 11, originalPriceUsd: 15, onSale: "sale", color: "", colorDetail: "", franchise: "", productType: "socks", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 74, name: "Performance Beanie", releaseDate: null, image: "74.jpg", imageHover: "74.jpg", imageDetail: "74.jpg", gender: "women", age: "", priceUsd: 9, originalPriceUsd: 18, onSale: "sale", color: "", colorDetail: "", franchise: "", productType: "beanie", brand: "originals", category: "accessories", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 75, name: "Powerlift.3.1 Shoes", releaseDate: null, image: "75.jpg", imageHover: "75hover.jpg", imageDetail: "75.jpg", gender: "women", age: "", priceUsd: 90, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "shoes", brand: "", category: "", sports: "weightlifting", miAdidas: "", teamName: "", partner: "" },
  { id: 76, name: "Powerlift.3.1 Shoes", releaseDate: null, image: "76.jpg", imageHover: "76hover.jpg", imageDetail: "76.jpg", gender: "women", age: "", priceUsd: 90, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "shoes", brand: "", category: "", sports: "weightlifting", miAdidas: "", teamName: "", partner: "" },
  { id: 77, name: "Golden Knights Vertical Heather Pullover", releaseDate: null, image: "77.jpg", imageHover: "77hover.jpg", imageDetail: "77.jpg", gender: "women", age: "", priceUsd: 38, originalPriceUsd: 75, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "", sports: "hockey", miAdidas: "", teamName: "", partner: "" },
  { id: 78, name: "Trefoil Hoodie", releaseDate: null, image: "78.jpg", imageHover: "78.jpg", imageDetail: "78.jpg", gender: "kids", age: "youth", priceUsd: 50, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "hodie", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 79, name: "Trefoil Hoodie Set", releaseDate: null, image: "79.jpg", imageHover: "79.jpg", imageDetail: "79.jpg", gender: "kids", age: "youth", priceUsd: 70, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 80, name: "SST Track Jacket", releaseDate: null, image: "80.jpg", imageHover: "80.jpg", imageDetail: "80.jpg", gender: "kids", age: "youth", priceUsd: 50, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "jackets", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 81, name: "Fleece Crew Sweatshirt", releaseDate: null, image: "81.jpg", imageHover: "81.jpg", imageDetail: "81.jpg", gender: "kids", age: "youth", priceUsd: 40, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "hoodies_sweatshirts", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 82, name: "SST Track Pants", releaseDate: null, image: "82.jpg", imageHover: "82.jpg", imageDetail: "82.jpg", gender: "kids", age: "youth", priceUsd: 40, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "pants", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 83, name: "Trefoil Tee", releaseDate: null, image: "83.jpg", imageHover: "83.jpg", imageDetail: "83.jpg", gender: "kids", age: "youth", priceUsd: 28, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "adicolor", productType: "short_sleeve_shirts", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 84, name: "Leggings", releaseDate: null, image: "84.jpg", imageHover: "84.jpg", imageDetail: "78.jpg", gender: "kids", age: "youth", priceUsd: 26, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "originals", category: "compression", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 85, name: "Mexico Away Jersey", releaseDate: null, image: "85.jpg", imageHover: "85.jpg", imageDetail: "78.jpg", gender: "boys", age: "youth", priceUsd: 70, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "jerseys", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 86, name: "Germany Away Jersey", releaseDate: null, image: "86.jpg", imageHover: "86.jpg", imageDetail: "78.jpg", gender: "boys", age: "youth", priceUsd: 70, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "jerseys", brand: "originals", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 87, name: "Ultraboost Shoes", releaseDate: null, image: "87.jpg", imageHover: "87.jpg", imageDetail: "78.jpg", gender: "kids", age: "youth", priceUsd: 140, originalPriceUsd: 160, onSale: "sale", color: "", colorDetail: "", franchise: "ultraboost", productType: "", brand: "", category: "shoes", sports: "running", miAdidas: "", teamName: "", partner: "" },
  { id: 88, name: "POD-S3.1 Shoes", releaseDate: null, image: "88.jpg", imageHover: "88.jpg", imageDetail: "78.jpg", gender: "kids", age: "infant_toddler", priceUsd: 50, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "podsystem", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 89, name: "Three Stripe Life Tee", releaseDate: null, image: "89.jpg", imageHover: "89.jpg", imageDetail: "78.jpg", gender: "girls", age: "youth", priceUsd: 25, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "apparel", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 90, name: "2-in-1 Space Dye Shorts", releaseDate: null, image: "90.jpg", imageHover: "90.jpg", imageDetail: "78.jpg", gender: "girls", age: "youth", priceUsd: 28, originalPriceUsd: null, onSale: "", color: "", colorDetail: "", franchise: "", productType: "", brand: "", category: "apparel", sports: "training", miAdidas: "", teamName: "", partner: "" },
  { id: 91, name: "adidas Z.N.E. Hoodie", releaseDate: null, image: "91.jpg", imageHover: "91hover.jpg", imageDetail: "91.jpg", gender: "women", age: "", priceUsd: 75, originalPriceUsd: 150, onSale: "sale", color: "", colorDetail: "", franchise: "zne", productType: "hodie", brand: "", category: "apparel", sports: "tennis", miAdidas: "", teamName: "", partner: "" },
  { id: 92, name: "adidas Z.N.E. Tee", releaseDate: null, image: "92.jpg", imageHover: "92hover.jpg", imageDetail: "92.jpg", gender: "men", age: "", priceUsd: 25, originalPriceUsd: 50, onSale: "sale", color: "", colorDetail: "", franchise: "zne", productType: "tee", brand: "athletics", category: "apparel", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 93, name: "Tubular Shadow Shoes", releaseDate: null, image: "93.jpg", imageHover: "93hover.jpg", imageDetail: "93.jpg", gender: "women", age: "", priceUsd: 100, originalPriceUsd: 0, onSale: "", color: "Đen", colorDetail: "LÕI ĐEN / PHẤN TRẮNG / RỐI HỒNG", franchise: "tubular", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
  { id: 94, name: "Tubular Shadow Shoes", releaseDate: null, image: "94.jpg", imageHover: "94hover.jpg", imageDetail: "94.jpg", gender: "women", age: "", priceUsd: 100, originalPriceUsd: 0, onSale: "", color: "Đỏ", colorDetail: "CHÚT SẪM / PHẤN TRẮNG / CHẠY TRẮNG", franchise: "tubular", productType: "", brand: "originals", category: "shoes", sports: "", miAdidas: "", teamName: "", partner: "" },
];
